local F, C = unpack(select(2, ...))

--MainMenuBar:Hide()
MainMenuBarTexture0:Hide()
MainMenuBarTexture1:Hide()
MainMenuBarTexture2:Hide()
MainMenuBarTexture3:Hide()
MainMenuBarLeftEndCap:Hide()
MainMenuBarRightEndCap:Hide()
MainMenuBarPageNumber:Hide()
MainMenuBarOverlayFrame:Hide()
print("character parent: "..CharacterMicroButton:GetParent():GetName())
